# Generated by Django 5.0.3 on 2024-04-03 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 12, 28, 15, 333147, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 12, 28, 15, 333147, tzinfo=datetime.timezone.utc)),
        ),
    ]
