# Generated by Django 5.0.3 on 2024-04-04 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_create_date_alter_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 4, 10, 0, 36, 887749, tzinfo=datetime.timezone.utc)),
        ),
    ]
