# Generated by Django 5.0.4 on 2024-04-05 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 9, 39, 33, 792437, tzinfo=datetime.timezone.utc)),
        ),
    ]
